AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: lambda-pytorch

Resources:
  InferenceFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Tracing: Active
      PackageType: Image
      Timeout: 30
      MemorySize: 1792 
      Events:
        HelloWorld:
          Type: HttpApi 
          Properties:
            Path: /inference
            Method: any
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./inference
      DockerTag: python3.8-v1

Outputs:
  InferenceApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
